import { writeFileSync } from 'node:fs';
import { basename, join, relative } from 'node:path';
import type { AssetManifest } from './manifest.js';
import { parseManifest } from './manifest.js';
import { segmentAsset, SEGMENT_S } from './segment.js';

/**
 * Turn an authored manifest into one the app can play.
 *
 * The authored manifest carries what a HUMAN measured — the asset, its
 * subtitles, its duration and its `content_windows`, the last of which needs an
 * eye on the frames either side of every cut and cannot be derived. This adds
 * what a MACHINE can derive: the segments.
 *
 * Kept separate from `segmentAsset` because the two answer different questions.
 * One cuts a file; this one decides what the app is told about the result, and
 * the app is told through `contracts.asset_manifest` rather than through a
 * hand-maintained list in `src/App.tsx` — which is what it was until R37, and
 * which drifts the moment anybody re-cuts the asset.
 */

export interface PrepareResult {
  manifest: AssetManifest;
  /** where the manifest was written */
  path: string;
  /** the init segment, which the app appends before any media segment */
  init_uri: string;
  /** the generated module the app imports */
  module_path: string;
}

export function prepareAsset(args: {
  /** the authored manifest, carrying the measured content_windows */
  manifestPath: string;
  manifestJson: string;
  /** where the segments go; also what the app will fetch them from */
  segmentDir: string;
  /** paths in the emitted manifest are relative to this, so they survive packaging */
  uriBase?: string;
  segmentSeconds?: number;
}): PrepareResult {
  const authored = parseManifest(args.manifestJson, args.manifestPath);

  const cut = segmentAsset(
    authored.media_uri,
    args.segmentDir,
    args.segmentSeconds ?? SEGMENT_S,
  );

  const base = args.uriBase ?? args.segmentDir;
  const manifest: AssetManifest = {
    ...authored,
    segments: cut.segments.map((s) => ({
      ...s,
      uri: toUri(s.uri, base),
    })),
  };

  const path = join(args.segmentDir, `${authored.asset_id}.manifest.json`);
  writeFileSync(path, `${JSON.stringify(manifest, null, 2)}\n`);

  const covered = manifest.segments?.[manifest.segments.length - 1]?.end_ms ?? 0;
  console.log(
    `INTERSTICE.prepare.done asset=${authored.asset_id}` +
      ` segments=${manifest.segments?.length ?? 0} covered_ms=${covered}` +
      ` duration_ms=${authored.duration_ms} file=${path}`,
  );

  // A segmented asset that does not reach its own declared end is a manifest
  // that will strand the player short of the credits with no error — the
  // `waiting` that never resolves. Worth a loud line rather than a silent pass.
  if (covered + 1_000 < authored.duration_ms) {
    console.log(
      `INTERSTICE.prepare.short covered_ms=${covered}` +
        ` duration_ms=${authored.duration_ms} — segments do not reach the declared end`,
    );
  }

  const module_path = writeSegmentModule(args.segmentDir, manifest, cut.init_uri);

  return { manifest, path, init_uri: toUri(cut.init_uri, base), module_path };
}

/**
 * Emit the static `require()`s the app needs.
 *
 * Metro resolves `require` at BUILD time, so a path computed at runtime bundles
 * nothing — the segment simply is not in the package, and the failure arrives on
 * the device as a fetch for a file that does not exist. The app therefore cannot
 * read the manifest and require what it names.
 *
 * Until R37 the answer was a hand-written list of four requires in
 * `src/App.tsx`, which drifts the moment anyone re-cuts the asset with a
 * different segment length. Generating the module keeps the requires static,
 * which metro needs, and keeps the timings derived, which correctness needs.
 */
function writeSegmentModule(
  segmentDir: string,
  manifest: AssetManifest,
  initPath: string,
): string {
  const rows = (manifest.segments ?? [])
    .map(
      (s) =>
        `  {index: ${s.index}, start_ms: ${s.start_ms}, end_ms: ${s.end_ms},` +
        ` mod: require('./${basename(s.uri)}')},`,
    )
    .join('\n');

  const source = `// GENERATED by pipeline/prepare.ts — do not edit.
// Regenerate with the pipeline; the timings come from the emitted HLS playlist,
// because ffmpeg cuts on keyframes and does not honour the requested length
// (_facts.yml limits.mse_buffer.segment_uneven).
/* eslint-disable */
export const INIT = require('./${basename(initPath)}');

export const SEGMENTS = [
${rows}
];
`;

  const path = join(segmentDir, 'segments.ts');
  writeFileSync(path, source);
  console.log(`INTERSTICE.prepare.module file=${path} segments=${manifest.segments?.length ?? 0}`);
  return path;
}

/**
 * Paths in the emitted manifest are relative to `base`, never absolute.
 *
 * An absolute build-machine path baked into a manifest that ships inside the
 * package is a path that exists on exactly one computer, and the failure lands
 * on the device as a fetch for a file that is not there.
 */
function toUri(path: string, base: string): string {
  const rel = relative(base, path);
  return rel.startsWith('..') ? basename(path) : rel;
}
